name: SortedFile

on: [push]

jobs:
  SortedFile:
  
   runs-on: ubuntu-latest
   
   steps:
   
     - name: Checkout
       uses: actions/checkout@v4
       
     - name: List
       run: ls -alh

     - name: ChangeMode
       run: chmod +x sortuniq.sh
     
     - name: RunScript
       run: ./sortuniq.sh fruits.txt
       
     - name: List
       run: ls -alh
       
     - name: Commit&push
       run: |
            git config --global user.name "mena_magdy"
            git config --global user.email "m.ayad@t-petra.com"
            git add sorted.txt
            git commit -m "Get Result from workflow"
            git push origin main
       
    