name: SortedFile

on: [push]

jobs:
  SortedFile:
  
   runs-on: ubuntu-latest
   
   steps:
   
     - name: Checkout
       uses: actions/checkout@v4
       
     - name: List
       run: ls -alh

     - name: ChangeMode
       run: chmod +x sortuniq.sh
     
     - name: RunScript
       run: ./sortuniq.sh fruits.txt
       
    